version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /hooks
    schedule:
      interval: weekly
    groups:
      hooks-pub:
        patterns:
          - "*"
