name: flutter_shader_hooks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason: ">=0.1.0-dev.50 <0.1.0"
  mason_logger: ^0.3.1
  path: ^1.8.3
  pubspec_parse: ^1.2.3
  yaml_edit: ^2.1.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.25.0
  very_good_analysis: ^6.0.0
